// Generated by scripts/optimize_images.py. Do not edit by hand.
export type Photo = { src: string; srcSet: string; width: number; height: number };

export const photos = {
  "portrait": {
    "src": "/images/portrait-1280.webp",
    "srcSet": "/images/portrait-640.webp 640w, /images/portrait-1280.webp 1280w",
    "width": 1280,
    "height": 1600
  },
  "huddle": {
    "src": "/images/huddle-1600.webp",
    "srcSet": "/images/huddle-800.webp 800w, /images/huddle-1600.webp 1600w",
    "width": 1600,
    "height": 1000
  },
  "coffee": {
    "src": "/images/coffee-1086.webp",
    "srcSet": "/images/coffee-600.webp 600w, /images/coffee-1086.webp 1086w",
    "width": 1086,
    "height": 1358
  }
} as const satisfies Record<string, Photo>;
