#!/usr/bin/env python3
"""Resize, crop, and re-encode source photos into web-ready WebP variants.

Reads originals from photos-src/, writes public/images/<name>-<w>.webp and a
typed manifest at app/lib/photos.ts. Re-encoding drops EXIF metadata, which
removes the GPS coordinates phone cameras embed. Run: npm run images
"""
import json
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "photos-src"
OUT = ROOT / "public" / "images"
MANIFEST = ROOT / "app" / "lib" / "photos.ts"

# name -> (source file, crop aspect as w/h or None, widths, focal point y 0..1)
PHOTOS = {
    "portrait": ("profile.jpg", 4 / 5, [640, 1280], 0.30),
    "huddle": ("volleyball_coach_team_huddle.JPEG", 16 / 10, [800, 1600], 0.55),
    "coffee": ("pouring_coffee.JPEG", 4 / 5, [600, 1200], 0.45),
}


def crop_to(im: Image.Image, aspect: float, focal_y: float) -> Image.Image:
    w, h = im.size
    if w / h > aspect:
        nw = round(h * aspect)
        left = (w - nw) // 2
        return im.crop((left, 0, left + nw, h))
    nh = round(w / aspect)
    top = min(max(round(focal_y * h - nh / 2), 0), h - nh)
    return im.crop((0, top, w, top + nh))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = {}
    for name, (fname, aspect, widths, focal_y) in PHOTOS.items():
        im = ImageOps.exif_transpose(Image.open(SRC / fname)).convert("RGB")
        if aspect:
            im = crop_to(im, aspect, focal_y)
        variants = []
        for w in widths:
            w = min(w, im.width)
            h = round(im.height * w / im.width)
            path = OUT / f"{name}-{w}.webp"
            im.resize((w, h), Image.Resampling.LANCZOS).save(path, "WEBP", quality=80, method=6)
            variants.append({"src": f"/images/{name}-{w}.webp", "w": w, "h": h, "kb": path.stat().st_size // 1024})
        big = variants[-1]
        manifest[name] = {
            "src": big["src"],
            "srcSet": ", ".join(f"{v['src']} {v['w']}w" for v in variants),
            "width": big["w"],
            "height": big["h"],
        }
        print(f"{name}: " + ", ".join(f"{v['w']}w {v['kb']}KB" for v in variants))

    MANIFEST.write_text(
        "// Generated by scripts/optimize_images.py. Do not edit by hand.\n"
        "export type Photo = { src: string; srcSet: string; width: number; height: number };\n\n"
        f"export const photos = {json.dumps(manifest, indent=2)} as const satisfies Record<string, Photo>;\n"
    )


if __name__ == "__main__":
    main()
